# Generated by Django 5.1.1 on 2024-09-28 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateField(default=datetime.datetime.today)),
                ('mileage_at_service', models.IntegerField()),
                ('worked_performed', models.CharField(max_length=10)),
                ('performed_by', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('inspection_result', models.CharField(max_length=10)),
                ('ag_rating', models.IntegerField()),
                ('inspection_date', models.DateField()),
                ('link_to_results', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.IntegerField(default='1')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('manufacture_year', models.IntegerField()),
                ('engine_code', models.CharField(max_length=10)),
                ('powertrain_power', models.IntegerField()),
                ('transmission_type', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='uploads/vin')),
            ],
        ),
    ]
