# Generated by Django 5.1.1 on 2024-09-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(default='', max_length=20)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('manufacture_year', models.CharField(max_length=4)),
                ('engine_code', models.CharField(max_length=10)),
                ('powertrain_power', models.CharField(max_length=5)),
                ('transmission_type', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='uploads/vin')),
                ('vin_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohistory.vin')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('inspection_result', models.CharField(choices=[('P1', 'Passed'), ('P2', 'Passed with minor Defects'), ('P3', 'Passed with major Defects'), ('F1', 'Failed due to minor Defects'), ('F2', 'Failed due to major Defects'), ('F3', 'Failed')], max_length=30)),
                ('ag_rating', models.CharField(max_length=30)),
                ('inspection_date', models.DateField()),
                ('link_to_results', models.CharField(max_length=200)),
                ('vin_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohistory.vin')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateField()),
                ('mileage_at_service', models.IntegerField()),
                ('worked_performed', models.CharField(max_length=200)),
                ('performed_by', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('vin_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohistory.vin')),
            ],
        ),
    ]
