# Generated by Django 5.1.1 on 2024-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='vin_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
