# Generated by Django 5.1.1 on 2024-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='ag_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vin',
            name='manufacture_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vin',
            name='powertrain_power',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='vin',
            name='vin_number',
            field=models.CharField(max_length=15),
        ),
    ]
