# Generated by Django 4.2.16 on 2024-10-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0002_alter_vin_vin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='vin_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='autohistory.vin'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_result',
            field=models.CharField(choices=[('PAS', 'Passed'), ('PMD', 'Passed with minor Defects'), ('PJD', 'Passed with major Defects'), ('FMD', 'Failed due to minor Defects'), ('FJD', 'Failed due to major Defects'), ('FAI', 'Failed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vin_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='autohistory.vin'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='vin_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='autohistory.vin'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='vin_number',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
