# Generated by Django 5.1.1 on 2024-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0002_alter_inspection_ag_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin',
            name='vehicle_id',
            field=models.CharField(default='', max_length=5),
        ),
    ]
