# Generated by Django 5.1.1 on 2024-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohistory', '0003_vin_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='vin_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='vin_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_service',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='performed_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='worked_performed',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ag_rating',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_result',
            field=models.CharField(choices=[('P1', 'Passed'), ('P2', 'Passed with minor Defects'), ('P3', 'Passed with major Defects'), ('F1', 'Failed due to minor Defects'), ('F2', 'Failed due to major Defects'), ('F3', 'Failed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='link_to_results',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vin',
            name='vehicle_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
